<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPBYMINW2457" name="MultDoubleTest" tests="3" failures="1" timestamp="11 Apr 2018 08:23:07 GMT" time="2.016" errors="0">
  <testcase name="sumDoubleTest" time="0.0" classname="com.epam.tat.module4.test.MultDoubleTest">
    <failure type="java.lang.AssertionError" message="defect founded in mult with double arguments expected [0.25] but found [0.0]">
      <![CDATA[java.lang.AssertionError: defect founded in mult with double arguments expected [0.25] but found [0.0]
	at com.epam.tat.module4.test.MultDoubleTest.sumDoubleTest(MultDoubleTest.java:26)
	at com.epam.tat.module4.test.runner.TestRunner.main(TestRunner.java:40)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- sumDoubleTest -->
  <testcase name="sumDoubleTest" time="1.016" classname="com.epam.tat.module4.test.MultDoubleTest"/>
  <testcase name="sumDoubleTest" time="1.0" classname="com.epam.tat.module4.test.MultDoubleTest"/>
</testsuite> <!-- MultDoubleTest -->
